### ISSUE TITLE
Some components generate annoying warnings

### ISSUE THREAD

**Issue by hazerbaker** [robeio/robe-react-ui#20]
![screen_shot_2016-12-09_at_16 00 42](https://cloud.githubusercontent.com/assets/24913690/21677886/42ae28c4-d34d-11e6-9e07-00c251ce4058.png)
![screen_shot_2016-12-09_at_16 03 56](https://cloud.githubusercontent.com/assets/24913690/21677887/42ae3d50-d34d-11e6-9245-a30c85ea36a0.png)

**Comment by hasanmumin** [comment]
"validationDisplay","sort","range" warnings fixed.
