### ISSUE TITLE
npm install is broken

### ISSUE THREAD

**Issue by skrobek** [robeio/robe-react-ui#28]
With current versions in package.json it's not possible to install dependencies:

```
npm ERR! peerinvalid The package react@15.4.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer google-map-react@0.22.3 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.4.1 wants react@^15.4.1
npm ERR! peerinvalid Peer react-bootstrap@0.30.7 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-dom@15.4.1 wants react@^15.4.1
npm ERR! peerinvalid Peer react-notifications@1.3.0 wants react@^0.14 || ^15.0.0
npm ERR! peerinvalid Peer react-quill@0.4.1 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-router@4.0.0-2 wants react@15.x
npm ERR! peerinvalid Peer react-select@0.9.1 wants react@^0.14.1
npm ERR! peerinvalid Peer recharts@0.20.2 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.7.0 wants react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x
npm ERR! peerinvalid Peer react-addons-transition-group@15.4.2 wants react@^15.4.2
```

**Comment by kbukum** [comment]
Hello skrobek , 

Can you share  with me npm and node version ? Also which are you using operation system ?

**Comment by skrobek** [comment]
@kbukum sure,

npm: `2.15.5`
node: `v4.4.5`
osx: `10.12.2 `

**Comment by kbukum** [comment]
@skrobek 

You can't start the project with this versions. You need to upgrade your npm and node programs. 
if you are using brew on OSX then you can use following commands to upgrade them.

brew update
brew upgrade node
npm install -g npm

Have a nice day.

**Comment by kbukum** [comment]
Note: 
You can find minimum version of npm in the package.json.

**Comment by kbukum** [comment]
@skrobek 

Can you let me know the state of the starting project after you upgrade npm and node programs. Then I can close the issue. 

Have a nice day.

**Comment by kbukum** [comment]
This issue is related by npm and node version. That's why I am closing the issue.
