### ISSUE TITLE
AjaxRequest

### ISSUE THREAD

**Issue by Appsido** [robeio/robe-react-ui#31]
Hi,

I try to change defaultProps. xhrFields of the AjaxRequest but it's not modified. Something wrong on my side with the following code:

`let readRequest = new AjaxRequest({
            url: "users",
            type: "GET",
            xhrFields: {
                withCredentials: false
            }
        });`

**Comment by kbukum** [comment]
Hello Appsido , 

Default Props of Ajax Request is is like that.

```json
 {
        type: "POST",
        dataType: "json",
        contentType: "application/json; charset=utf-8",
        xhrFields: {
            withCredentials: true
        },
        async: true,
        crossDomain: true
    };

```
and I tried your code and create AjaxRequest and after AjaxRequest props changed like below.

```json
{ type: 'GET',
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        xhrFields: { withCredentials: false },
        async: true,
        crossDomain: true,
        url: 'users' 
}
```

As I see the props of AjaxRequest changed.  Can you give me more detail about what you tried to do.  Can you give me details of the request from Request Header by Using FireBug or something like that.

**Comment by Appsido** [comment]
Sorry my bad, in fact i had an issue on my side not at all related to your lib
