### ISSUE TITLE
when I press enter, page should not reload

### ISSUE THREAD

**Issue by ahmetMesut** [robeio/robe-react-ui#33]

**Comment by ahmetMesut** [comment]
when only one field in the form  and press 'enter' page reloading

**Comment by hasanmumin** [comment]
Please explain a bit more.

**Comment by serayuzgur** [comment]
@ahmetMesut Please describe the issue? Which components did you use? I can't reproduce the issue.

**Comment by serayuzgur** [comment]
It happens when dataform has one component and user makes a keyPress to Enter
