### ISSUE TITLE
DataGrid sorunları

### ISSUE THREAD

**Issue by onurarslan** [robeio/robe-react-ui#34]
Showcase incelemesinde aşağıda ki sorunları tespit ettim.

**DataGrid (Custom Toolbar and Pagination)**
1) Gösterilecek kayıt sayısı 1 yapılmasına rağmen pagination çalışmıyor
2) custom buttonu çalışmıyor.

**DataGrid (CRUD Toolbar)**
1) **Edit ekranı sorunları:**
--Gender bölümünde cinsiyetler türkçe yazılmış.
--Data Grid'de tarih kısmı bugünün tarihi setli gelmiş gözüküyor ama edit de ilgili tarih setli gelmiyor.
2) **Password**: Password alanına göre filtreleme yapılıyor. Bu güvenlik açısından güvenilir bir filtreleme olmayabilir.
3) **Birthdate, Job Title, Gender kolon sorunları**: Bu alanlara veri girdiğimde search filtreleme yapmıyor. Örneğin gender bölümünde cinsiyete göre filtreleme yapmıyor.

**Comment by hasanmumin** [comment]
DataGrid (Custom Toolbar and Pagination)
* 1 ile ilgili sorun giderildi.
* 2 ile ilgili örnek click eklendi.

DataGrid (CRUD Toolbar)

* Edit ekranı sorunları çözüldü.
* 2 ve 3 model içinde search mekanizması ile ilgili. Hali hazırda search ignore gibi mekanizmalar mevcut. Bunlar ile iligli detaylı dökümantasyon eklenecektir.
