### ISSUE TITLE
Strict Mode Hatası

### ISSUE THREAD

**Issue by onurarslan** [robeio/robe-react-ui#35]
Proje ilk defa çalıştırılmak istendiğinde MultierImpl.js(102. satır) ve Utility.js(143. satır)  strict mode hatası vermektedir. Çözüm için MultierImpl.js dosyasının 102. satırına ve Utility.js'nin 139. satırına **"use strict";** ifadesi eklendikten sonra proje sağlıklı şekilde çalışmaktadır. İlk hatayla ilgili ekran görüntüsü aşağıda  yer almaktadır.
![screenshot from 2017-01-13 23-33-44](https://cloud.githubusercontent.com/assets/8824755/21944866/09915602-d9e1-11e6-8255-fd13f14def50.png)

**Comment by kbukum** [comment]
Merhaba ,

Kullandığınız versiyondan kaynaklı bu hata alınmaktadır. Package.json içerisinde tanımlı olan versiyonların aşağıdasındaki versiyonları kullanmamanızı öneririz.

**Comment by kbukum** [comment]
Console^dan okudugum kadarıyl node versiyonu v4.2.6 olarak görünmektedir. Şuanki package.json dosyasında tanımlı minimum versiyon 6.0 olarak belirtilmiştir. Mümkünse 6.0 ile yeniden deneyip dönüş yapabilir misiniz ?
