### ISSUE TITLE
Can't load i18n data

### ISSUE THREAD

**Issue by recepkoseoglu** [robeio/robe-react-ui#38]
If i18n is not loaded in the project it gives the following error inside components.
<img width="708" alt="screen shot 2017-01-16 at 12 20 03" src="https://cloud.githubusercontent.com/assets/17153637/21977294/37388a68-dbde-11e6-816b-fa0bdd94d99c.png">

**Comment by serayuzgur** [comment]
You can see the usage from showcase/docs/i18n
