### ISSUE TITLE
Toast should have  click on close 

### ISSUE THREAD

**Issue by ahmetMesut** [robeio/robe-react-ui#41]
* **Robe React UI Version:** 1.1.17
* **Node Version:** v7.4.0
* **OS / Version:** MacOS Sierra 10.12.2
* **Browsers / Versions:** Version 55.0.2883.95 (64-bit)

### Expected behavior
Toast should have closeOnClick feature

### Actual behavior
Nothing happens

**Comment by serayuzgur** [comment]
click on close is the default behavior now.
