### ISSUE TITLE
decimal input does not have increase and decrease button

### ISSUE THREAD

**Issue by ahmetMesut** [robeio/robe-react-ui#44]
* **Robe React UI Version:** 1.1.17
* **Node Version:** v7.4.0
* **OS / Version:** MacOS Sierra 10.12.2
* **Browsers / Versions:** Chrome / Version 55.0.2883.95 (64-bit)

### Expected behavior
I think in decimal input need to be increase and decrease button.
### Actual behavior
in decimal input does not have increase and decrease button.

**Comment by hasanmumin** [comment]
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
