### ISSUE TITLE
add a prop/flag to make toasts be restricted to numMaxVisible

### ISSUE THREAD

**Issue by mikedevita** [robeio/robe-react-ui#5]
a lot of times users don't want to spam the UI with all the toast messages, instead it'd be a nice optional feature to restrict the numVisible to a number of some sort, allowing a queue type setup.

**Comment by mikedevita** [comment]
you can see how I implemented something similar [here](https://github.com/RelativeMedia/rackcatio-frontend/tree/development/src/containers/Notification) although it doesn't quite work right when clearing some/all

**Comment by hasanmumin** [comment]
Documentation updated.
http://robeio.github.io/robe-react-ui/#Docs/Toast
Thanks for your recommend.
