### ISSUE TITLE
Password Strength

### ISSUE THREAD

**Issue by cagataysahin** [robeio/robe-react-ui#54]
I think we can create a password strength for security in PasswordInput.It should be include weak,okay,good and strong parts.
<img width="1280" alt="aaaa" src="https://cloud.githubusercontent.com/assets/25481785/22510269/04a0471c-e89a-11e6-983e-211118476635.png">

**Comment by hasanmumin** [comment]
http://robeio.github.io/robe-react-ui/#Components/inputs/PasswordInput
