### ISSUE TITLE
Robe react ui 1.1.20 DataGrid error

### ISSUE THREAD

**Issue by MustafaGungor** [robeio/robe-react-ui#63]
My DataGrid :==

![image](https://cloud.githubusercontent.com/assets/20699497/22881368/caa96c1a-f1ee-11e6-862b-8badec31509b.png)

My Datagrid image=
![datagridimage](https://cloud.githubusercontent.com/assets/20699497/22881415/034e06de-f1ef-11e6-94f4-480a654838f2.jpg)

How can i solve?

**Comment by MustafaGungor** [comment]
The same problem applies in 1.1.21

**Comment by serayuzgur** [comment]
Please take a look at [i18n](http://robeio.github.io/robe-react-ui/#Docs/i18n). You have to load language data.

**Comment by MustafaGungor** [comment]
thank you for answered.
