### ISSUE TITLE
Toast does not seem to work with IE11. 

### ISSUE THREAD

**Issue by NKJo28** [robeio/robe-react-ui#66]
* **Robe React UI Version:** 1.1.33
* **Robe React Commons: Version:** 1.0.85 (Seems to be bundled after running npm install of UI)
* **React Version:** 15.4.2 with addons
* **Node Version:** 7.7.1
* **OS / Version:** Win7 x64
* **Browsers / Versions:** Internet Explorer 11

### Expected behavior
This command:  `import Toast from "robe-react-ui/lib/toast/Toast";`
should work, as it does in Chrome and Firefox through my testing.

### Actual behavior
I haven't tested any other components, but the import statement for Toast causes an error on IE 11. I wonder if IE is supported.

The error is `SCRIPT5007: Unable to get property 'constructor' of undefined or null reference`
Apologies but I'm a newbie so I don't exactly know how to post logs and stack trace in a way that is useful, so I'll just copy the chain of require calls that lead to it:
```
var _App = __webpack_require__(19); 
var _Toast = __webpack_require__(85);
var _robeReactCommons = __webpack_require__(16);
var _ShallowComponent = __webpack_require__(14);
var _class = __webpack_require__(72);
var ClassInstance = new _Class2.default();
```

Which leads to:
```
var Class = function () {
    function Class() {
        _classCallCheck(this, Class);

        this.bindAll(this);
    }
    _createClass(Class, [{
        key: "bindAll",
        value: function bindAll(instance) {
            var list = ["Object", "ReactComponent", "Component", "Class", "Date", "File"];
            var parent = Object.getPrototypeOf(instance);
            var bindedKeys = [];
            while (list.indexOf(parent.constructor.name) === -1) {
                var names = Object.getOwnPropertyNames(parent);
                for (var i = 0; i < names.length; i += 1) {
                    var name = names[i];
                    var restrictMethods = instance instanceof _react.Component ? reactMethods : es6Methods;
                    if (restrictMethods.indexOf(name) === -1 && _Assertions2.default.isFunction(instance[name])) {
                        if (!bindedKeys[name]) {
                            instance[name] = instance[name].bind(instance);
                            bindedKeys[name] = true;
                        }
                    }
                }
                parent = Object.getPrototypeOf(parent);
            }
        }
    }]);

    return Class;
}();
```
`while (list.indexOf(parent.constructor.name) === -1)` is what causes the error, somehow parent is null after a few iterations because `parent = Object.getPrototypeOf(parent);` returns null.

To work around this, I tried to use "require" instead of "import", but that causes Toast to be undefined for all browsers, only import seems to work.

**Comment by recepkoseoglu** [comment]
function.name not supported in IE bug fixed

**Comment by NKJo28** [comment]
That was really fast, thanks!

**Comment by recepkoseoglu** [comment]
We would like to thank you for your feedback
